version: "3"

services:
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - "mongo"
    command: nodemon /usr/src/app/src/server.js

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
